import type { Metadata } from "next";
import { quicksand } from "@/app/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Recipe & Meals Sharing App",
  description: "Generated by Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
